지도 달력화면 개선
Central-MakeUs/OpenOff-Client pull request #30
Opened 2023-07-21 09:10 UTC by JoStar33

### PR Type

- [x] 💫 기능추가
- [x] 🐛 버그수정

### OS별 테스트 여부

- [x] android
- [ ] ios

### 작업 내용

- 달력화면에 헤더 타이틀이 정상적으로 보이지않던 이슈 수정.
- 달력화면 UI 일부 수정(버튼 간격, 달력 크기)

### 링크

- resolved #29 

### 기타 사항

-

2023-07-22 15:32 UTC, yeonju0110 requested changes
css 조금 수정해야할 것 같아서 코멘트 남겨놨습니다 :) 이상있으면 말씀해주세요 🥹 🙌

2023-07-22 15:32 UTC, yeonju0110 commented on src/navigators/Navigator.tsx
>            headerStyle: {
- 헤더 부분에 Back 글자를 지울 수 있나요? figma상에는 뒤로가기 버튼 아이콘만 있어서요 🤔
- 헤더 아랫부분에 border를 없애줘야할 것 같아요!

2023-07-22 15:32 UTC, yeonju0110 commented on src/screens/eventMap/DatePickScreen/DatePickScreen.tsx
>            label="적용"
'적용', '초기화' 글씨는 body2 style가 아니라 h4 style이 적용되어야 하는 것 같은데 확인해주세요! :)
그리고 borderRadius도 27.5이어야 하는데 20 정도로 되어있는 것 같아요!
위치도 하단에 위치해야하는데 위쪽에 위치한 것 같은 느낌이 듭니다!

그리고 figma에는 '기간'이라는 헤더가 있는데 누락된 것 같습니다!

2023-07-22 19:21 UTC, yeonju0110 commented on src/navigators/Navigator.tsx
>            headerStyle: {
이 두가지는 제가 이벤트 개설 만들면서 같이 수정할거라 신경안쓰셔도 될 것 같아요!!! 👀

2023-07-23 06:36 UTC, JoStar33 commented on src/navigators/Navigator.tsx
>            headerStyle: {
넵 감사합니다!!

2023-07-23 06:37 UTC, JoStar33 commented on src/screens/eventMap/DatePickScreen/DatePickScreen.tsx
>            label="적용"
앗 넵 알겠습니다 해당 내용 수정해서 반영해놓을게요ㅎㅎ

2023-07-23 07:03 UTC, JoStar33 commented
수정사항 반영 완료했습니다! 풀리퀘 합칠게요~!

2023-07-23 07:03 UTC, merged