Permission 파일 위치 변경 및 알림리스트 화면 구현
Central-MakeUs/OpenOff-Client pull request #47
Opened 2023-07-30 13:01 UTC by JoStar33

### PR Type

- [x] 💫 기능추가
- [x] 🐛 버그수정

### OS별 테스트 여부

- [x] android
- [x] ios

### 작업 내용

- permission파일의 위치를 services폴더로 이동하였습니다.
- data내에 일부 파일을 mocks폴더로 이동시키는 작업을 수행했습니다.
- 알림 리스트에 보이는 카드를 구현했습니다.
- 알림 리스트 화면을 구현하였습니다.
- 네비게이션 파일에 보이던 merge 오류 코드를 수정했습니다.

### 링크

- resolved #45 
- resolved #41 

### 기타 사항

- getPixelSize 함수를 제가 이번 풀리퀘에서 구현한 파일들에 적용시켜두었습니다!
- 풀리퀘를 분리에서 열지않고 한 브랜치에서 일괄 처리시켰어요...!

2023-07-30 21:25 UTC, yeonju0110 requested changes
하하.,, 아니 잽싸게 폰트 바꿔놓으셔서 놀랐습니다,, 🤣 ,, 심지어 다시 또 돌아와있네요..?
역시 빠른 죠스타.. 수고하셨습니다!!! css 조금만 수정요청했습니당 :)

2023-07-30 21:25 UTC, yeonju0110 commented on src/models/alert/AlertType.ts
> +export type AlertType = 'CA' | 'EA';
알림 타입이 두가지만 존재하나요?.?
노션에다가 혹은 주석으로 설명적어두면 좋을 것 같아요! :)

2023-07-30 21:25 UTC, yeonju0110 commented on src/screens/home/AlertScreen/AlertScreen.style.ts
> +    flexDirection: 'column',
기본값이 column이라 해당 코드는 필요없어 보입니다!

2023-07-30 21:25 UTC, yeonju0110 commented on src/screens/home/AlertScreen/AlertScreen.tsx
> +    <View style={alertScreenStyles.container}>
오호 이 녀석은 ScrollView가 아닌가요?!

2023-07-30 21:25 UTC, yeonju0110 commented on src/components/home/cards/AlertCard/AlertCard.style.ts
> +    flexDirection: 'column',
이것도 기본값이 column이라 필요없어 보이구, `gap: 3`정도가 추가되어야 할 것 같슴다!!

2023-07-30 21:26 UTC, yeonju0110 commented on src/models/alert/AlertType.ts
> +export type AlertType = 'CA' | 'EA';
왜냐면,,제가 사용할 것이기 때문에.,,, 🥹

2023-07-31 00:51 UTC, JoStar33 commented on src/models/alert/AlertType.ts
> +export type AlertType = 'CA' | 'EA';
아아 이거 우선 여기다가 설명 한번 쭉 드릴게요!
저희 기획서를 확인해보시면 아시겠지만 알림 리스트쪽 아이콘이 딱 두개로 나뉘어져 있어요!
- 메가폰 아이콘
- 댓글 아이콘
그래서 저는 기획자와 디자이너가 알림의 형태를 크게 댓글과 이벤트로 생각한다고 봤고
- 이벤트: 찜한 이벤트, 주최한 이벤트, 신청한 이벤트
- 댓글: 댓글
이렇게 판단하여 알림 타입을 아래와 같이 정하게 됐습니다ㅎㅎ
- CA: Comment Alert
- EA: Event Alert

2023-07-31 00:54 UTC, JoStar33 commented on src/screens/home/AlertScreen/AlertScreen.style.ts
> +    flexDirection: 'column',
이게 제가 최상단마저도 column이라 작성하는게 습관이돼서...하하,,.ㅎㅎㅎㅎ안좋은 습관이죠 참.. 빠르게 고쳐놓을게요!!

2023-07-31 00:55 UTC, JoStar33 commented on src/components/home/cards/AlertCard/AlertCard.style.ts
> +    flexDirection: 'column',
넵 반영해둘게요!

2023-07-31 00:58 UTC, JoStar33 commented on src/screens/home/AlertScreen/AlertScreen.tsx
> +    <View style={alertScreenStyles.container}>
이것도 살짝 투머치 토킹으로 왜 이렇게 했는지 말씀드리자면...
이게 첼과 논의했을때 이벤트 알림의 최대갯수를 정하고 최대갯수를 넘어갈시에 서버에서 가장 늦게 등록된 알림을 삭제하는 방향을 고려했었거든요! 그래서 쭉 늘어진 알림리스트를 고려안해도 된다!라고 생각하여 View라고 했던건데...
생각을 해보니까 또 기기별로 정해진 알림리스트라 하더라도 짤릴수도 있는거잖아요? 제가 생각이 짧았네요😥 ScrollView로 반영해둘게요!

2023-07-31 01:03 UTC, JoStar33 commented on src/models/alert/AlertType.ts
> +export type AlertType = 'CA' | 'EA';
주석도 추가해둘게요!

2023-07-31 01:38 UTC, JoStar33 commented
말씀해주신 사항들 반영완료했어요~! 수정하다보니 code쪽으로 alertType값들을 넣어두는게 좋겠다 싶어서 이동하는 작업까지 같이 수행했어요🙂

2023-07-31 10:19 UTC, yeonju0110 commented on src/models/alert/AlertType.ts
> +export type AlertType = 'CA' | 'EA';
네!! 이해했습니다~~!! 감사합니다 😄😄😄

2023-07-31 10:19 UTC, yeonju0110 commented on src/screens/home/AlertScreen/AlertScreen.tsx
> +    <View style={alertScreenStyles.container}>
아하 ㅠㅠ 이해했습니다!! 네네 감사함당 👀

2023-07-31 10:20 UTC, yeonju0110 approved these changes
확인했습니다!!! 같이 타입 분리해둔 거 좋은 것 같아요!! 수고하셨습니당 🥹👍🏻👍🏻👍🏻

2023-07-31 11:01 UTC, merged