🔀 지도화면 개선
Central-MakeUs/OpenOff-Client pull request #67
Opened 2023-08-04 13:15 UTC by JoStar33

### PR Type

- [x] 💫 기능추가

### OS별 테스트 여부

- [x] android
- [x] ios

### 작업 내용

- 지도 바텀시트 이미지를 3장에서 5장으로 개선했습니다.
- 이벤트 상세 페이지에서 지도화면으로 넘어오는 케이스를 고려했습니다.
- 좌표 색상을 main으로 변경하였습니다.

### 링크

- resolved #64 

### 기타 사항

- 제인이 사전에 말해주셨던 "carousel로 스크롤 이벤트가 겹치는 문제 해결하는 법"을 반영해봤어요~!

2023-08-06 21:23 UTC, yeonju0110 requested changes
이미지 다 볼 수 있어서 좋네요 ! ! 😁 수정 요청 사항 코멘트 달아놨습니다~!!

2023-08-06 21:23 UTC, yeonju0110 commented on src/types/apps/menu.ts
> +    eventId: string;
하단 탭을 이용해서 접근할 때는 eventId가 없으니,
`string | undefined;`나 `string | null`로 바꾸는 게 좋을 것 같은데, 어떻게 생각하시나요? 👀

2023-08-06 21:23 UTC, yeonju0110 commented on src/screens/eventMap/EventMapScreen/EventMapScreen.tsx
> +  }, [params.eventId]);
현재 하단탭을 눌러서 접근할 때는 eventId가 없어서 에러가 뜹니다 🥹

2023-08-06 21:23 UTC, yeonju0110 commented on src/components/eventMap/cards/MapEventCard/MapEventCard.tsx
> +          panGestureHandlerProps={{ minDist: 20 }}
이미지가 작아서 그런지 20은 너무 크게 느껴지네요,, 10정도는 어떠신지요?? 🤔

2023-08-06 23:58 UTC, JoStar33 commented on src/types/apps/menu.ts
> +    eventId: string;
오 네네 이벤트 id 없이 접근하는 경우가 있는데 너무 배제했네요 빠르게 반영할게요!

2023-08-06 23:59 UTC, JoStar33 commented on src/components/eventMap/cards/MapEventCard/MapEventCard.tsx
> +          panGestureHandlerProps={{ minDist: 20 }}
아하! 저도 안그래도 너무 큰가 고민했었는데 알겠습니다 10으로 조정해볼게요~!~!

2023-08-07 02:05 UTC, JoStar33 commented
수정사항 모두 반영해뒀고 내친김에 쿼리 파라미터까지 미리 만들어봤어요! 머릿속에서 계속 상상만 했던건데 직접 만들라니 시간이 좀 걸렸네요ㅎㅎ

2023-08-07 15:29 UTC, yeonju0110 approved these changes
확인했습니다!! 쿼리파라미터 흥미롭네요 ㅎㅎ 근데 약간 길어서 hook으로 뺄 수 있으면 빼면 좋을 것 같기도 하군요..? 🤔 수고하셨습니다!!! 👍🏻👍🏻👍🏻

2023-08-08 00:03 UTC, merged