로그인 & 회원가입 API 적용하기(1/2)
Central-MakeUs/OpenOff-Client pull request #73
Opened 2023-08-09 00:58 UTC by JoStar33

### PR Type

- [x] 💫 기능추가

### OS별 테스트 여부

- [x] android
- [ ] ios

### 작업 내용

- access & refresh 토큰과 로그인 유무 정보를 담아둘 수 있는 스토어를 구현했습니다.
- 소셜로그인 일반로그인에 API를 적용시켰습니다.
- refresh API를 fetcher에 적용시켰습니다.
- 회원가입시 이메일 중복체크를 하는 API를 적용시켰습니다.
- sms인증 API를 적용시켰습니다.
- 구현에 필요한 DTO들을 작성해두었습니다.

### 링크

- resolved #71 

### 기타 사항

- 일단 현재까지 붙여놓은 API들은 refresh제외하고 모두 정상동작하는거 확인했어요~!
- 승쪽이랑 얘기를 좀 나눠보니까, 일반회원가입시 이메일 비밀번호 입력 후에 이용약관 페이지로 넘어가고 다시 뒤로가기를 눌러 이메일 비밀번호를 누르게해선 안되겠더라구요! 그래서 이용약관 페이지에서는 뒤로가기가 막히도록 만들었어요ㅎㅎ

2023-08-10 02:13 UTC, yeonju0110 requested changes
ㅠㅠ 신경쓸 게 많았을 것 같아요, 수고하셨습니다!! 👍🏻👍🏻👍🏻👍🏻
궁금한 점들 코멘트 남겨놨습니다 😁

2023-08-10 02:13 UTC, yeonju0110 commented on src/screens/authorize/joins/InterestFieldScreen/InterestFieldScreen.tsx
> +  const handleAuthorize = () => {
이 부분도 아래처럼 끊어서 작성하는 게 나을 것 같긴 합니다! 🤔
```ts
const handleAuthorize = async () => {
    const data: ConcludeOnBoardingProps = {
      onBoarding: {
        nickname: '',
        username: '',
        gender: 'MAN',
        year: 0,
        month: 0,
        day: 0,
      },
      fields: {
        fieldTypeList: interestField
          .filter((fieldElement) => fieldElement.isActive)
          .map((field) => field.value),
      },
    };

    await concludeOnBoarding(data);

    dispatch({
      type: UserInfoStatus.SET_INTEREST_FIELD,
      interestField: interestField.filter(
        (fieldElement) => fieldElement.isActive,
      ),
    });

    navigation.navigate(AuthorizeMenu.JoinComplete);
  };
```

2023-08-10 02:13 UTC, yeonju0110 commented on src/screens/authorize/joins/PhoneCertificationScreen/PhoneCertificationScreen.tsx
> +        handlePress: () =>
이 친구는 따로 분리안하고 다시 넣은 이유가 있을까요?!

2023-08-10 02:13 UTC, yeonju0110 commented on src/screens/authorize/logins/LoginScreen/LoginScreen.tsx
> +  const handleKakaoLogin = () => {
요 부분도 아래처럼 작성할 수 있을 것 같은데, 어떨까요?! 🤔
```ts
 const handleKakaoLogin = async () => {
    const result = await loginWithKakaoAccount();
    const data = await socialLogin({
      socialType: 'kakao',
      token: result.idToken,
    });
    divergeAuthorizeFlow(data.data?.userInfo.userName);
  };
```

2023-08-10 02:13 UTC, yeonju0110 commented on src/stores/Authorize.ts
access token도 저장해놓는 이유가 있을까요?! refresh만 저장해두면 될 것 같아서요! 👀

2023-08-10 02:21 UTC, JoStar33 commented on src/hooks/queries/auth.ts
> +        return getMyInfo();
앗 이렇게 했던 이유는 로딩이 실행되는걸 일괄적으로 처리하고싶어서 이렇게 만들었어요!

2023-08-10 13:21 UTC, JoStar33 commented
말씀해주신 사항들과 더불어서 로그인 & 회원가입 & 아이디 비밀번호 찾기에 대한 모든 API 적용을 다해봤습니다!! 확인해주시면 감사하겠슴다ㅎㅎ,,,!

2023-08-11 00:48 UTC, yeonju0110 commented
생일칸이 눌리지 않습니다! @JoStar33

2023-08-11 06:19 UTC, JoStar33 commented
다이얼로그 포탈 제거 및 생일칸 이슈까지 수정했어요! @yeonju0110

2023-08-12 06:55 UTC, JoStar33 commented
찐막으로 한번만 다시 검토해주실 수 있을까요...?🥺🥺🥺 modal을 react-native-paper로 바꿔봤어요...ㅠㅠ @yeonju0110

2023-08-12 07:14 UTC, yeonju0110 commented
혹시 늦게 봐도 괜찮을까요?! 오늘은 확인 못해서요🥲🥲

2023-08-12 07:16 UTC, JoStar33 commented
아 그럼요 그럼요 알겠슴다!!

2023-08-12 20:07 UTC, yeonju0110 approved these changes
확인했습니다!! 모달 잘 작동합니다 🥹 PR하셔도 될 것 같아요! 수고하셨습니다~!!

2023-08-13 02:13 UTC, JoStar33 commented
감사합니다!!ㅎㅎ

2023-08-13 02:13 UTC, merged