🔀 이벤트 명단 페이지 (1/2)
Central-MakeUs/OpenOff-Client pull request #76
Opened 2023-08-11 12:47 UTC by yeonju0110

### PR Type

- [x] 💫 기능추가

### OS별 테스트 여부

- [ ] android
- [x] ios

### 작업 내용

- 이벤트 명단 페이지 퍼블리싱
- api 연동
  - 주최한 이벤트 티켓
  - 이벤트 콘솔 페이지
  - 주최자 명단 페이지

### 링크

- #59
- #61

### 기타 사항

- 일단 죄송합니다.. 퍼블리싱만 하려다가 급발진해서 api까지 붙였습니다,,,
- api 수정이 필요한 부분이랑, 추가 질문 답변 페이지는 추후에 다시 올리겠습니다!
- 죠스타가 디비 날려서,,,,,, 볼 수 없을건데,,,,,여튼,, PR 올립니다!! 😞

2023-08-12 02:45 UTC, JoStar33 requested changes
고생많으셨어요 제인ㅎㅎㅎ 코드 작성하시느라 엄청 고생하셨겠네요ㅜㅜ
간단한 코멘트들 몇개 달아봤습니다!!!

2023-08-12 02:45 UTC, JoStar33 commented on src/screens/userEvent/HostLedgerScreen/HostLedgerScreen.tsx
> +    (x) => x.data.content,
x말고 page라는 명칭은 어떠실까요🖐️

2023-08-12 02:45 UTC, JoStar33 commented on src/screens/userEvent/UserEventScreen/UserEventScreen.tsx
> +  const flatHostEventList = hostEventList?.pages.flatMap((x) => x.data.content);
여기도 page가 좋아보입니다!!

2023-08-12 03:08 UTC, yeonju0110 commented on src/components/userEvent/host/SelectBottomSheet/SelectBottomSheet.tsx
> +      (props: any) => (
앗 요거 공식문서에서 가져온 거였어서 깜빡했네요ㅠㅠ 타입을 한번 찾아보겠습니다!!

2023-08-12 03:09 UTC, yeonju0110 commented on src/screens/userEvent/HostLedgerScreen/HostLedgerScreen.tsx
> +    (x) => x.data.content,
앗 좋습니다🙌🏻

2023-08-12 03:10 UTC, yeonju0110 commented on src/components/userEvent/host/SelectBottomSheet/SelectBottomSheet.tsx
> +    const snapPoints = useMemo(() => ['24%'], []);
네네 이친구도 같이 지정하겠습니다!!!

2023-08-12 20:21 UTC, yeonju0110 commented
말씀하신 부분들 수정해놨습니다! 🙌

2023-08-13 01:58 UTC, JoStar33 approved these changes
확인했습니다! 고생많으셨어요!!👍👍👍

2023-08-13 02:38 UTC, merged